In [1]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_csv("hf://datasets/lars1234/story_writing_benchmark/gemma2.csv")

/Users/tildeidunsloth/Desktop/Thesis/Thesis_project/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# subset langauge = en
df_en = df[df['language'] == "en"]
df_en = df_en[df_en['generation_type'] == "scene_beginning"]

In [3]:
df_en["target_word_count"].mean()

np.float64(721.6363636363636)

In [4]:
len(df_en)

1320

In [14]:
df_en

,prompt_id,prompt,story_text,target_word_count,language,theme,time_period,generation_type,model_name,temperature,...,q9,q10,q11,q12,q13,q14,q15,q_translation,length_score,overall_score
8,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"The sun had just dipped below the horizon, cas...",965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,2,3,2,2,3,3,3,0,5,3.0000
9,p6d7d0bcdf6,Write the first scene (approximately 965 words...,It was a moonless night in the bustling city o...,965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,1,2,1,2,2,3,1,0,5,2.5000
20,pa882c87e43,Write the first scene (approximately 812 words...,"The city of Neo-Metropolis, a sprawling metrop...",812,en,crime,the distant future,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,2,3,2,2,3,3,2,0,4,2.9375
21,pa882c87e43,Write the first scene (approximately 812 words...,The city of Neo-Metropolis was a bustling hub ...,812,en,crime,the distant future,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,1,2,2,2,2,3,2,0,4,2.5625
50,p41ea35f989,Write the first scene (approximately 794 words...,"The sun had long set over the vast, barren lan...",794,en,historical fiction,the distant future,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,2,2,2,2,2,3,2,0,5,2.7500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8485,p012a673bd6,Write the first scene (approximately 520 words...,"In the heart of Victorian London, where gas la...",520,en,adventure,Victorian England,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,2,3,2,2,3,3,3,0,5,3.0625
8494,p2cb68c6192,Write the first scene (approximately 560 words...,"The fog had settled upon London like a shroud,...",560,en,crime,Victorian England,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,2,3,2,2,3,3,3,0,5,3.1250
8495,p2cb68c6192,Write the first scene (approximately 560 words...,"In the fog-kissed streets of Victorian London,...",560,en,crime,Victorian England,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,3,3,3,3,3,3,3,0,5,3.5000
8512,pdc90084e53,Write the first scene (approximately 812 words...,"In the heart of ancient Rome, where marble col...",812,en,supernatural,ancient Rome,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,2,3,2,2,3,3,2,0,5,2.9375
8513,pdc90084e53,Write the first scene (approximately 812 words...,"In the heart of ancient Rome, where marble col...",812,en,supernatural,ancient Rome,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,1,3,1,3,3,3,3,0,5,3.0000

In [13]:
df_en["prompt"].value_counts()

prompt
Write the first scene (approximately 965 words) of a story about "supernatural" set in the renaissance. Create an engaging beginning that establishes the setting and introduces key characters.             120
Write the first scene (approximately 812 words) of a story about "crime" set in the distant future. Create an engaging beginning that establishes the setting and introduces key characters.                 120
Write the first scene (approximately 794 words) of a story about "historical fiction" set in the distant future. Create an engaging beginning that establishes the setting and introduces key characters.    120
Write the first scene (approximately 535 words) of a story about "adventure" set in the present day. Create an engaging beginning that establishes the setting and introduces key characters.                120
Write the first scene (approximately 928 words) of a story about "dystopian" set in the renaissance. Create an engaging beginning that establishes the setting and introduces key characters.                120
Write the first scene (approximately 730 words) of a story about "western" set in the distant future. Create an engaging beginning that establishes the setting and introduces key characters.               120
Write the first scene (approximately 559 words) of a story about "magic" set in medieval times. Create an engaging beginning that establishes the setting and introduces key characters.                     120
Write the first scene (approximately 723 words) of a story about "horror" set in the present day. Create an engaging beginning that establishes the setting and introduces key characters.                   120
Write the first scene (approximately 520 words) of a story about "adventure" set in Victorian England. Create an engaging beginning that establishes the setting and introduces key characters.              120
Write the first scene (approximately 560 words) of a story about "crime" set in Victorian England. Create an engaging beginning that establishes the setting and introduces key characters.                  120
Write the first scene (approximately 812 words) of a story about "supernatural" set in ancient Rome. Create an engaging beginning that establishes the setting and introduces key characters.                120
Name: count, dtype: int64

In [17]:
# make a subset with this specific prompt
df_unique_prompt = df[df["prompt"] == """Write the first scene (approximately 965 words) of a story about "supernatural" set in the renaissance. Create an engaging beginning that establishes the setting and introduces key characters."""]

In [18]:
df_unique_prompt

,prompt_id,prompt,story_text,target_word_count,language,theme,time_period,generation_type,model_name,temperature,...,q9,q10,q11,q12,q13,q14,q15,q_translation,length_score,overall_score
8,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"The sun had just dipped below the horizon, cas...",965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,2,3,2,2,3,3,3,0,5,3.0000
9,p6d7d0bcdf6,Write the first scene (approximately 965 words...,It was a moonless night in the bustling city o...,965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.50,...,1,2,1,2,2,3,1,0,5,2.5000
150,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"The sun had just dipped below the horizon, cas...",965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.75,...,1,2,1,2,2,3,2,0,5,2.6250
151,p6d7d0bcdf6,Write the first scene (approximately 965 words...,It was a moonless night in the bustling city o...,965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,0.75,...,2,3,3,2,2,3,2,0,5,2.9375
292,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"The sun had just dipped below the horizon, cas...",965,en,supernatural,the renaissance,scene_beginning,AMead10/c4ai-command-r-08-2024-awq,1.00,...,1,2,1,2,2,3,2,0,5,2.5625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8103,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"In the heart of Venice, where the canals weave...",965,en,supernatural,the renaissance,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,0.75,...,2,2,2,2,3,3,2,0,5,2.8750
8244,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"In the heart of Florence, where the scent of f...",965,en,supernatural,the renaissance,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.00,...,2,2,2,2,2,3,2,0,5,2.7500
8245,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"In the heart of Venice, where the canals weave...",965,en,supernatural,the renaissance,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.00,...,2,3,2,2,3,3,2,0,5,2.8750
8386,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"In the heart of Renaissance Florence, where th...",965,en,supernatural,the renaissance,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,2,2,3,2,3,3,3,0,5,3.0000
8387,p6d7d0bcdf6,Write the first scene (approximately 965 words...,"In the heart of Venice, where the canals weave...",965,en,supernatural,the renaissance,scene_beginning,Orion-zhen/aya-expanse-8b-AWQ,1.25,...,2,3,2,3,3,3,3,0,5,3.0625

In [6]:
df2 = pd.read_json("hf://datasets/BoltMonkey/stories_by_complexity/data/train/train.json")

In [15]:
len(df2)

15533

In [7]:
df2["genre_style"].value_counts()

genre_style
speculative           1308
historical            1294
classic               1290
cute                  1276
adventure             1272
travel                1266
alternate universe    1265
fiction               1264
dramatic              1262
educational           1260
fable                 1260
sci-fi                1259
sweet                 1256
funny                 1251
mystery               1246
suspenseful           1245
scary                 1245
silly                 1235
inspirational         1231
philosophical         1229
cautioning            1225
traditional           1220
fantasy               1217
day-in-the-life       1183
folktale              1097
Name: count, dtype: int64

In [8]:
df2 = df2[df2["voice"] == "3rd person"]

In [11]:
df2["prompt"].value_counts()

prompt
All of the characters in the story should be from the medieval ages and the main character overcomes nervousness.                                                2
Most of the characters in the story should be in positions of power and the main character wants to know more.                                                   2
Some of the characters in the story should be scientists and the main character travels somewhere new.                                                           2
Most of the characters in the story should be recently introduced to each other and the main character goes out with somebody they admire.                       2
All of the characters in the story should be sensible and the main character loses gracefully.                                                                   2
                                                                                                                                                                ..
Most of the characters in the story should be spies and the main character does something terrible without realising it.                                         1
Most of the characters in the story should be ordinary people and the main character starts a project and experiences a coincidence.                             1
Some of the characters in the story should be old people and the main character has a common but seldom discussed dilemma.                                       1
Most of the characters in the story should be passionately interested in a topic and the main character builds something and wonders about something complex.    1
All of the characters in the story should be farmers and the main character befriends someone from a different culture.                                          1
Name: count, Length: 15493, dtype: int64

In [9]:
# count number of tokens in "text"
len(df2["text"])

15533

In [19]:
df2

,reading_age_suitability,theme_appropriate,reading_complexity,title,prompt,text,genre_style,voice,tense,flesch_kincaid_index,gunning_fog_index,smog_index,automated_reading_index
11,4,4,4.2650,The Wobbly Stick,Most of the characters in the story should be ...,"Once upon a time in the future, there were thr...",cautioning,3rd person,future tense,2.5,4.66,5.9,4.0
12,4,4,4.9700,The Haunted Attic,Some of the characters in the story should be ...,There was an old lady named Mrs. Brown who liv...,scary,3rd person,past tense,3.4,5.38,6.4,4.7
15,4,4,4.4675,The Little Athlete,Most of the characters in the story should be ...,"Once upon a time, there was a little boy named...",traditional,3rd person,past tense,2.4,5.57,5.2,4.7
48,5,4,5.8775,No More Stuff,Most of the characters in the story should be ...,"Once upon a time, there was a person named Sar...",speculative,3rd person,present tense,4.2,6.41,6.8,6.1
51,5,5,5.1625,The Happy Monster,Most of the characters in the story should be ...,"Once upon a time, there was a happy monster na...",speculative,3rd person,past tense,3.5,5.65,6.4,5.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31146,16,16,11.8750,The Haunted Tent,Most of the characters in the story should be ...,As the sun sets and the last rays of daylight ...,scary,3rd person,future tense,12.0,14.15,11.5,15.7
31149,16,16,7.9500,The Masked Crush,All of the characters in the story should be i...,"Emily can't believe it's Halloween already, he...",sweet,3rd person,present tense,6.4,7.90,8.4,9.1
31150,16,16,9.5200,The Koala's Keeper,Some of the characters in the story should be ...,"As the sun rose over the Australian bushland, ...",adventure,3rd person,past tense,7.7,9.68,10.0,10.7
31151,16,16,12.0000,The Quest,Most of the characters in the story should be ...,Sophie had it all - a high-paying job in one o...,classic,3rd person,past tense,12.2,14.42,12.0,15.4
31152,16,16,9.9900,A Farmer's Unlikely Friendship,All of the characters in the story should be f...,"In a small town in rural Australia, there live...",silly,3rd person,future tense,8.6,10.26,10.1,11.0

In [15]:
# Count words for all rows in the dataframe
df2["num_words"] = df2["text"].apply(lambda x: len(x.split()))

# Total words across all rows
total_words = df2["num_words"].sum()
print("Total words:", total_words)

Total words: 5624965